GET http://localhost:3000/
###
GET http://localhost:3000/w
###
GET http://localhost:3000/api/
###
GET http://localhost:3000/api/stateList
###
GET http://localhost:3000/api/stateFindONE/7
###
POST http://localhost:3000/api/stateInsert
Content-Type: application/json

{
"id":7,
"name":"harambe",
"code":"005",
"city":"kakamega county-matungu sub-county"
}
###
PUT http://localhost:3000/api/stateUpdate/7
Content-Type: application/json

{
"name":"zanziba",
"code":"tz001",
"city":"zanziba"
}
###
DELETE http://localhost:3000/api/stateDelete/8
###
GET http://localhost:3000/api/cityList
###
GET http://localhost:3000/api/cityFindONE/14
###
POST http://localhost:3000/api/cityInsert
Content-Type: application/json

{

"name":"Mali",
"state_id":9,
"address":"mali123",
"state":"Nyali",
"restorand":"Alhamdullillah"
}
###
GET http://localhost:3000/api/cityFindONE/1
###
PUT http://localhost:3000/api/cityUpdate/22
Content-Type: application/json

{
"name":"madina",
"address":"madina2323",
"state":"answar"
}
###
DELETE http://localhost:3000/api/cityDelete/22