GET http://localhost:3000/
###
GET http://localhost:3000/api/w
###
GET http://localhost:3000/api/
###
GET http://localhost:3000/api/stateList
###
GET http://localhost:3000/api/stateFindONE/1
###
POST http://localhost:3000/api/stateInsert
Content-Type: application/json

{
"id":45,
"name":"harambe",
"code":"005",
"city":"kakamega county-matungu sub-county"
}
###
PUT http://localhost:3000/api/stateUpdate/1
Content-Type: application/json

{
"name":"zanziba",
"code":"tz001",
"city":"zanziba"
}
###
DELETE http://localhost:3000/api/stateDelete/8
###
GET http://localhost:3000/api/cityList
###
GET http://localhost:3000/api/cityFindONE/1
###
POST http://localhost:3000/api/cityInsert
Content-Type: application/json

{

"name":"Mali",
"state_id":1,
"address":"mali123",
"state":"Nyali",
"restorand":"Alhamdullillah"
}
###
GET http://localhost:3000/api/cityFindONE/1
###
PUT http://localhost:3000/api/cityUpdate/4
Content-Type: application/json

{
"name":"madina",
"address":"madina2323",
"state":"answar"
}
###
DELETE http://localhost:3000/api/cityDelete/3
###
GET http://localhost:3000/api/categoryList
###
GET http://localhost:3000/api/categoryFindONE/1
###
POST http://localhost:3000/api/categoryInsert
Content-Type: application/json

{
"name":"nuts",
"menu_item":"groundnuts"
}
###
GET http://localhost:3000/api/categoryFindONE/1
###
PUT http://localhost:3000/api/categoryUpdate/1
Content-Type: application/json

{
"name":"food",
"menu_item":"pilau"
}
###
DELETE http://localhost:3000/api/categoryDelete/5
###
GET http://localhost:3000/api/stateList
###
GET http://localhost:3000/api/stateFindONE/7
###
POST http://localhost:3000/api/stateInsert
Content-Type: application/json

{
"id":11,
"name":"harambe",
"code":"005",
"city":"kakamega county-matungu sub-county"
}
###
PUT http://localhost:3000/api/stateUpdate/10
Content-Type: application/json

{
"name":"zanziba",
"code":"tz001",
"city":"zanziba"
}
###
DELETE http://localhost:3000/api/stateDelete/10
###
GET http://localhost:3000/api/addressList
###
GET http://localhost:3000/api/addressFindONE/6
###
POST http://localhost:3000/api/addressInsert
Content-Type: application/json

{

"name":"Mali",
"state_id":9,
"address":"mali123",
"state":"Nyali",
"restorand":"Alhamdullillah"
}
###
GET http://localhost:3000/api/addressFindONE/1
###
PUT http://localhost:3000/api/addresssUpdate/22
Content-Type: application/json

{
"name":"madina",
"address":"madina2323",
"state":"answar"
}
###
DELETE http://localhost:3000/api/cityDelete/22
###
GET http://localhost:3000/api/status_catalogList
###
GET http://localhost:3000/api/status_catalogFindONE/1
###
POST http://localhost:3000/api/status_catalogInsert
Content-Type: application/json

{
"name":"pilau",
"order_status":"pending"
}
###
PUT http://localhost:3000/api/status_catalogUpdate/2
Content-Type: application/json

{
"name":"pilau",
"order_status":"delivered"
}
###
DELETE http://localhost:3000/api/status_catalogDelete/1
###
GET http://localhost:3000/api/addressList
###
GET http://localhost:3000/api/addressFindONE/6
###
DELETE http://localhost:3000/api/addressDelete/1
###
POST http://localhost:3000/api/addressInsert
Content-Type: application/json

{
    "street_address_1":"23332",
    "street_address_2":"744579",
    "zip_code":"hdgg43",
    "delivery_instructions":"ontime",
    "user_id":1,
    "city_id":1,
    "created_at":"2023-03-03",
    "updated_at":"2024-02-02",
    "city":"Nairobi",
    "users":"34",
    "orders":"3"
}
###
GET http://localhost:3000/api/userList
###
POST http://localhost:3000/api/userInsert
Content-Type: application/json

{
  "name":"Abdirahman",
    "contact_phone":"076489230",
    "phone_verified":true,
    "email":"sadque@gmail.com",
    "email_verified":"123wu",
    "confirmation_code":"weyu34",
    "password":"kmshjgfdfjh3784",
    "created_at":"2024-03-02T00:00:00Z",
    "updated_at":"2024-03-02T00:00:00Z",
    "address":"sadque234",
    "comment":"fine",
    "driver":"kms",
    "orders":"23",
    "restaurant_owner":"sadque"
}
###
http://localhost:3000/api/userFindONE/1
###
PUT http://localhost:3000/api/userUpdate/2
Content-Type: application/json

{
"email":"sadque@jhs",
"orders":"21"
}
###
DELETE http://localhost:3000/api/userDelete/1
###
GET http://localhost:3000/api/commentList
###
http://localhost:3000/api/commentFindONE/1
###
PUT http://localhost:3000/api/commentUpdate/2
Content-Type: application/json

{
"is_praise":true,
"users":"90"
}
###
DELETE http://localhost:3000/api/driverDelete/1
###
GET http://localhost:3000/api/driverList
###
GET http://localhost:3000/api/driverFindONE/1
###
PUT http://localhost:3000/api/driverUpdate/2
Content-Type: application/json

{
"car_year":"2024",
"users":"95"
}
###
POST http://localhost:3000/api/driverInsert
Content-Type: application/json

{
 
}
###
DELETE http://localhost:3000/api/menuDelete/1
###
GET http://localhost:3000/api/menuList
###
GET http://localhost:3000/api/menuFindONE/2
###
PUT http://localhost:3000/api/menuUpdate/2
Content-Type: application/json

{
"price":"3232",
"name":"Biriani"
}
###
POST http://localhost:3000/api/menuInsert
Content-Type: application/json

{
 
}
###
DELETE http://localhost:3000/api/ordermDelete/1
###
GET http://localhost:3000/api/ordermList
###
GET http://localhost:3000/api/ordermFindONE/1
###
PUT http://localhost:3000/api/ordermUpdate/5
Content-Type: application/json

{
"menu_item":"pilau",
"orders":"3545"
}
###
POST http://localhost:3000/api/ordermInsert
Content-Type: application/json

{
 
}
###
DELETE http://localhost:3000/api/ordersDelete/8
###
GET http://localhost:3000/api/ordersList
###
GET http://localhost:3000/api/ordersFindONE/8
###
PUT http://localhost:3000/api/ordersUpdate/8
Content-Type: application/json

{
"orders":"223",
"status_catalog": "ordered"
}
###
POST http://localhost:3000/api/ordersInsert
Content-Type: application/json

{
 
}
###
DELETE http://localhost:3000/api/orderDelete/1
###
GET http://localhost:3000/api/orderList
###
GET http://localhost:3000/api/orderFindONE/6
###
PUT http://localhost:3000/api/orderUpdate/6
Content-Type: application/json

{
"price":"223000",
"discout":"1000",
"final_price":"222000"
}
###
POST http://localhost:3000/api/orderInsert
Content-Type: application/json

{
 
}
###
DELETE http://localhost:3000/api/restaurantDelete/1
###
GET http://localhost:3000/api/restaurantList
###
GET http://localhost:3000/api/restaurantFindONE/2
###
PUT http://localhost:3000/api/restaurantUpdate/1
Content-Type: application/json

{
"name":"ma shaa Allah",
"street_address":"riyadh125",
"city":"Makkah"
}
###
POST http://localhost:3000/api/restaurantInsert
Content-Type: application/json

{
"id": 1,
    "name": "ma shaa Allah",
    "street_address": "riyadh125",
    "zip_code": "347843yy",
    "city_id": 1,
    "created_at": "2023-04-05",
    "updated_at": "2024-06-05",
    "menu_item": "beverage",
    "orders": "3",
    "city": "Makkah",
    "restaurand_owner": "Sadque"
}
###
DELETE http://localhost:3000/api/restaurantoDelete/1
###
GET http://localhost:3000/api/restaurantoList
###
GET http://localhost:3000/api/restaurantoFindONE/1
###
PUT http://localhost:3000/api/restaurantoUpdate/2
Content-Type: application/json

{
"restaurant_id":1,
"user_id":1
}
###
POST http://localhost:3000/api/restaurantoInsert
Content-Type: application/json

{
  "restaurant_id":2,
  "owner_id":1,
  "users_id":"34",
  "restaurant":"Alhamdullillha"
}
###
GET http://localhost:3000/api/userList
###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
 "name": "Abdirahman",
    "contact_phone": "0762435635",
    "phone_verified": true,
    "email": "sadque@jfkd",
    "email_verified": true,
    "confirmation_code": "233223ew",
    "password": "sadq3233",
    "address": "madina33232",
    "comment": "fine ",
    "driver": "hjhxd",
    "orders": "34",
    "restaurant_owner": "Alli "

}
###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "user_id":5,
   "username":"Abdi",
    "password":"kms@",
    "role":"adm"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "username":"Abdi",
    "password":"kms@"
}
###
GET http://localhost:3000/api/auth/list
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBYmRpIiwicm9sZSI6ImFkbSIsImV4cCI6MTcxODI5NTI2NX0.2D8zXGsjfvnDJy-7lzUMMRR-oFeO-x3f8rW2A6-h0fo
###
GET http://localhost:3000/api/auth/find_one/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBYmRpIiwicm9sZSI6ImFkbSIsImV4cCI6MTcxODI5NTI2NX0.2D8zXGsjfvnDJy-7lzUMMRR-oFeO-x3f8rW2A6-h0fo
###
DELETE http://localhost:3000/api/auth/delete/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBYmRpIiwicm9sZSI6ImFkbSIsImV4cCI6MTcxODI5NTI2NX0.2D8zXGsjfvnDJy-7lzUMMRR-oFeO-x3f8rW2A6-h0fo
###
PUT http://localhost:3000/api/auth/update/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBYmRpIiwicm9sZSI6ImFkbSIsImV4cCI6MTcxODI1NzcwM30.qq-IuPTVcSo0eDiaptvnAydd_WZFq6TMCsxv3WQbHF4

{
"name":"Abdirahman Alli",
"address":"43434Ryadh",
"comment":"Alhamdullillah"
}
###
GET http://localhost:3000/api/join